version: "3.7"

services:
  app:
    build: docker
    container_name: "php-app"
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
    working_dir: /app

  nginx:
    image: nginx
    container_name: "nginx"
    working_dir: /app
    ports:
      - "8080:80"
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  clickhouse:
    image: yandex/clickhouse-server
    container_name: "clickhouse"
    ports:
      - "8123:8123"
    volumes:
      - ./db/clickhouse:/var/lib/clickhouse
